name: trackit_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^1.1.6
  get_it: ^7.6.4
  intl: ^0.18.0
  json_annotation: ^4.8.1
  # mapbox_maps_flutter: ^0.5.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/LatoSemiBold.ttf
          weight: 600
